# Conda environment file for meshlearn.
name: meshlearn
channels:
  - defaults
  - conda-forge
dependencies:
  - lightgbm >= 3.2
  - igl >= 2.2
  - scikit-learn >= 1.0
  - trimesh >= 3.0
  - pandas >= 1.3
  - psutil >= 5.0
  - matplotlib >= 3.5
  - nibabel >= 2.1
  - pytest >= 7.0
  - pytest-console-scripts >= 1.3
  - tensorflow >= 2.9
  - pip
  - pip:
    - brainload >= 0.3
    - coverage >= 6.0


